version: '3'

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: "digital_library"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  digital-library:
    image: digital-library-digital-library
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/digital_library?serverTimezone=UTC
      - TOKEN_SECRET=jwtappdemo
      - TOKEN_EXPIRED=3600000
